name: Build OP12 Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl git-lfs gnupg flex bison gperf libsdl1.2-dev libesd0-dev squashfs-tools build-essential zip ccache libncurses5-dev zlib1g-dev openjdk-11-jre openjdk-11-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev g++-multilib lib32z1-dev lib32ncurses5-dev gcc-multilib maven tmux screen w3m ncftp rsync libssl-dev

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir -p ~/op12_kernel && cd ~/op12_kernel
          repo init -u https://github.com/op12-evolution-x/kernel_manifest -b vic --git-lfs
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build KernelSU and SukiSU
        run: |
          cd ~/op12_kernel
          source build/envsetup.sh
          lunch lineage_waffle-bp1a-user
          mka bootimage
